#pragma once

#define CDP_DISK_FILTER_DEVICE_TYPE 0x9A40

#define IOCTL_CDP_DISK_FILTER_CONFIGURE CTL_CODE( \
	CDP_DISK_FILTER_DEVICE_TYPE, 0x801, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_CDP_DISK_FILTER_DISABLE CTL_CODE( \
	CDP_DISK_FILTER_DEVICE_TYPE, 0x802, METHOD_BUFFERED, FILE_WRITE_DATA)
#define IOCTL_CDP_DISK_FILTER_QUERY CTL_CODE( \
	CDP_DISK_FILTER_DEVICE_TYPE, 0x803, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_CDP_DISK_FILTER_DIAGNOSE CTL_CODE( \
	CDP_DISK_FILTER_DEVICE_TYPE, 0x804, METHOD_BUFFERED, FILE_READ_DATA)
#define IOCTL_CDP_DISK_FILTER_RECORDS CTL_CODE( \
	CDP_DISK_FILTER_DEVICE_TYPE, 0x805, METHOD_BUFFERED, FILE_READ_DATA)

#define CDP_DISK_FILTER_CONFIG_VERSION 6UL
#define CDP_DISK_FILTER_MAX_DIAGNOSTIC_INSTANCES 16UL
#define CDP_DISK_FILTER_MAX_RECORDS_PER_QUERY 128UL

typedef struct _CDP_DISK_FILTER_CONFIG
{
	ULONG Version;
	ULONG DiskNumber;
	ULONG PartitionStyle;
	ULONG MbrSignature;
	GUID DiskGuid;
	ULONG SectorSize;
	ULONG Reserved;
	ULONGLONG DiskLength;
	ULONGLONG SourceStart;
	ULONGLONG SourceLength;
	ULONGLONG JournalStart;
	ULONGLONG JournalLength;
} CDP_DISK_FILTER_CONFIG, *PCDP_DISK_FILTER_CONFIG;

typedef struct _CDP_DISK_FILTER_DISABLE
{
	ULONG Version;
	ULONG DiskNumber;
	ULONG PartitionStyle;
	ULONG MbrSignature;
	GUID DiskGuid;
	ULONG SectorSize;
} CDP_DISK_FILTER_DISABLE, *PCDP_DISK_FILTER_DISABLE;

typedef struct _CDP_DISK_FILTER_QUERY
{
	ULONG Version;
	ULONG DiskNumber;
	ULONG PartitionStyle;
	ULONG MbrSignature;
	GUID DiskGuid;
	ULONG SectorSize;
} CDP_DISK_FILTER_QUERY, *PCDP_DISK_FILTER_QUERY;

typedef struct _CDP_DISK_FILTER_STATUS
{
	ULONG Version;
	ULONG DiskNumber;
	ULONG PartitionStyle;
	ULONG MbrSignature;
	GUID DiskGuid;
	ULONG Enabled;
	ULONG SectorSize;
	ULONGLONG DiskLength;
	ULONGLONG SourceStart;
	ULONGLONG SourceLength;
	ULONGLONG JournalStart;
	ULONGLONG JournalLength;
	ULONGLONG JournalBytesUsed;
	ULONGLONG MappingItemCount;
} CDP_DISK_FILTER_STATUS, *PCDP_DISK_FILTER_STATUS;

typedef struct _CDP_DISK_FILTER_DIAGNOSTIC_REQUEST
{
	ULONG Version;
	ULONG DiskNumber;
	ULONG PartitionStyle;
	ULONG MbrSignature;
	GUID DiskGuid;
	ULONG SectorSize;
} CDP_DISK_FILTER_DIAGNOSTIC_REQUEST,
	*PCDP_DISK_FILTER_DIAGNOSTIC_REQUEST;

typedef struct _CDP_DISK_FILTER_DIAGNOSTIC_ENTRY
{
	ULONG InstanceIndex;
	LONG DeviceNumberStatus;
	ULONG DeviceNumber;
	LONG IdentityReadStatus;
	ULONG ActualMbrSignature;
	GUID ActualGptDiskGuid;
	ULONG IdentityMatches;
	ULONG LowerDeviceType;
	ULONG LowerStackSize;
	ULONG FilterStackSize;
} CDP_DISK_FILTER_DIAGNOSTIC_ENTRY,
	*PCDP_DISK_FILTER_DIAGNOSTIC_ENTRY;

typedef struct _CDP_DISK_FILTER_DIAGNOSTIC_REPLY
{
	ULONG Version;
	ULONG AttachedInstanceCount;
	ULONG ReturnedInstanceCount;
	ULONG RequestedDiskNumber;
	ULONG RequestedPartitionStyle;
	ULONG RequestedMbrSignature;
	GUID RequestedDiskGuid;
	ULONG RequestedSectorSize;
	CDP_DISK_FILTER_DIAGNOSTIC_ENTRY
		Instances[CDP_DISK_FILTER_MAX_DIAGNOSTIC_INSTANCES];
} CDP_DISK_FILTER_DIAGNOSTIC_REPLY,
	*PCDP_DISK_FILTER_DIAGNOSTIC_REPLY;

typedef struct _CDP_DISK_FILTER_RECORDS_REQUEST
{
	ULONG Version;
	ULONG DiskNumber;
	ULONGLONG StartIndex;
} CDP_DISK_FILTER_RECORDS_REQUEST,
	*PCDP_DISK_FILTER_RECORDS_REQUEST;

typedef struct _CDP_DISK_FILTER_RECORD_ENTRY
{
	ULONGLONG Index;
	ULONGLONG WallClock100ns;
	ULONGLONG VolumeOffset;
	ULONGLONG JournalOffset;
	ULONGLONG Sequence;
	ULONG DataLength;
	ULONG Flags;
} CDP_DISK_FILTER_RECORD_ENTRY,
	*PCDP_DISK_FILTER_RECORD_ENTRY;

typedef struct _CDP_DISK_FILTER_RECORDS_REPLY
{
	ULONG Version;
	ULONG DiskNumber;
	ULONGLONG TotalCount;
	ULONGLONG StartIndex;
	ULONG ReturnedCount;
	ULONG Reserved;
	CDP_DISK_FILTER_RECORD_ENTRY
		Records[CDP_DISK_FILTER_MAX_RECORDS_PER_QUERY];
} CDP_DISK_FILTER_RECORDS_REPLY,
	*PCDP_DISK_FILTER_RECORDS_REPLY;
